### ISSUE TITLE
Allow distribution

### ISSUE THREAD

**Issue by Ozelzotz** [mineblock11/snow-under-trees-remastered#2]
Hello, I wanted to use this mod on a server however I cant add the mod because the server is being rented from a server host and since this mod doesnt have the "Allow distribution" toggle enabled even though it is under an MIT license I am unable to add it to the server. Could you please flip the toggle in the license tab so i can use it on a server? Thanks :)

[https://support.curseforge.com/en/support/solutions/articles/9000207877-project-distribution-toggle]

**Comment by mineblock11** [comment]
I cannot enable distribution as it would allow malware sites to automatically republish my mods with malware.
